config/routes.rb
Rails.application.routes.draw do

  resources :hotels do
    resources :rooms, except: [:index], shallow: true do
      resources :bookings , except: [:index]
      end
  end
  root 'hotels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  validates :room_price, presence: true
  validates :total_price, presence: true
  validates :booking_code, presence: true, uniqueness: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  before_validation :generate_booking_code, on: :create
  before_validation :room_price_for_booking
  before_validation :calculate_total_price


  def generate_booking_code
    loop do
      random_code = rand(1...100)
      new_code = "%02d" % random_code
      unless Booking.exists?(booking_code: new_code)
        self.booking_code = new_code
        break
      end
    end
  end


  def calculate_total_price
    return unless start_date.present? && end_date.present?
    self.total_price = room.price_per_night * (end_date.to_date - start_date.to_date).to_i
  end

  def room_price_for_booking
    return  unless room.price_per_night.present?
    self.room_price = room.price_per_night.freeze
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings, dependent: :destroy
  validates :room_code, uniqueness: true, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, except: [:new, :create]
  before_action :set_room, only: [:new, :create]


  def new
    @booking = Booking.new
  end
  def edit
  end

  def create
    @booking = @room.bookings.build(booking_params)
    @booking.generate_booking_code
    if @booking.save
      flash[:notice] = "Booked Successfully"
      redirect_to @booking.room
    else
      render 'new', status: :unprocessable_entity
    end
  end
  def update
    if @booking.update(booking_params)
      flash[:notice] = "Booking updated Successfully"
      redirect_to @booking.room
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_back fallback_location: @booking.room
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :booking_code, :total_price,)
  end

  def set_booking
    @booking = Booking.find_by(id: params[:id])

    unless @booking
      flash[:alert] = "Booking not found"
      redirect_to root_path
    end
  end

  def set_room
    @room = Room.find_by(id: params[:room_id])

    unless @room
      flash[:alert] = "Room not found"
      redirect_to root_path
    end
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [ :show, :edit, :update, :destroy ]

  def index
    @hotels = Hotel.all
  end

  def show
  end

  def new
    @hotel = Hotel.new
  end

  def edit
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      flash[:notice] = "Hotel Successfully Created"
      redirect_to hotels_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @hotel.update(hotel_params)
      flash[:notice] = "Hotel Updated Successfully"
      redirect_to hotels_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @hotel.destroy
    redirect_to hotels_path
  end

  private

  def set_hotel
    @hotel = Hotel.find_by(id: params[:id])

    unless @hotel
      flash[:alert] = "Hotel not found"
      redirect_to root_path
    end
  end

  def hotel_params
    params.require(:hotel).permit(:name, :address, :description)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_hotel, only:[:new, :create]
  before_action :set_room, only: [:edit, :update, :show , :destroy]


  def show
  end

  def edit
  end

  def new
    @room = Room.new
  end

  def create
    @room = @hotel.rooms.build(room_params)
    if @room.save
      flash[:notice] = "Room Successfully Created For #{@hotel.name} Hotel"
      redirect_to @room.hotel
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Room Successfully Updated For #{@room.hotel.name} Hotel"
      redirect_to @room.hotel
    else
      render 'edit', status: :unprocessable_entity
    end
  end


  def destroy
    @room.destroy
    redirect_back fallback_location: hotels_path
  end

  private

  def room_params
    params.require(:room).permit(:room_code, :description,:price_per_night)
  end

  def set_room
    @room = Room.find_by(id: params[:id])

    unless @room
      flash[:alert] = "Room not found"
      redirect_to root_path
    end
  end

  def set_hotel
    @hotel = Hotel.find_by(id: params[:hotel_id])

    unless @hotel
      flash[:alert] = "Hotel not found"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/_booking.html.erb
<div class="booking">
  <p><strong>Booking Code:</strong> <%= booking.booking_code %></p>
  <p><strong>Start Date:</strong> <%= booking.start_date.strftime('%A, %B %e, %Y %l:%M %p') %></p>
  <p><strong>Start Date:</strong> <%= booking.end_date.strftime('%A, %B %e, %Y %l:%M %p') %></p>
  <p><strong>Room Price:</strong> <%= number_to_currency(booking.room_price) %></p>

  <%= link_to "Edit Booking", edit_booking_path(booking) %> --
  <%= link_to "Delete Booking", booking, data:{ turbo_method: :delete, turbo_confirm: "Are you sure?"}%>--
  <%= link_to "Back to Room #{@room.hotel.name}", @room.hotel %>
</div>

app/views/bookings/_form.html.erb
<%= form_for [@room, @booking] do |form| %>

  <%= form.label :start_date %>
  <%= form.datetime_local_field :start_date, value: @booking.start_date&.strftime('%Y-%m-%dT%H:%M') %>

  <%= form.label :end_date %>
  <%= form.datetime_local_field :end_date, value: @booking.end_date&.strftime('%Y-%m-%dT%H:%M') %>

  <%= form.submit "Create Booking" %>
<% end %>

app/views/bookings/edit.html.erb
<h1> Edit Book For <%= @booking.room.room_code %> Room</h1>


<%= render 'bookings/form', booking: @booking %>

app/views/bookings/new.html.erb
<h1>Make Booking For <%= @room.room_code %> room code</h1>

<%= render 'shared/errors', obj: @booking %>
<%= render 'form' %>

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p>
    <strong>Name:</strong>
    <%= hotel.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= hotel.address %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= hotel.description %>
  </p>

</div>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel %> |
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/index.html.erb
<h1>Hotels</h1>


<% @hotels.each do |hotel| %>
  <%= render hotel %>
  <p>
    <%= link_to "Show this hotel", hotel %>
  </p>
  <h3>____________________________________</h3>
<% end %>


<%= link_to "New hotel", new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'shared/errors', obj: @hotel %>
<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/show.html.erb
<%= render @hotel %>

<h2>Room's for <%= @hotel.name %> </h2>
<% @hotel.rooms.each do |room| %>
  <h3>________________________________</h3>
  <%= render 'rooms/room', room: room %>
  <%= link_to "edit", edit_room_path(room) %>--
  <%= link_to "Delete", room_path(room), data: {turbo_method: :delete, turbo_confirm: "Are you Sure?"}%>--
  <%= link_to "Add Book For This Room", new_room_booking_path(room) %>--
  <%= link_to "Booking list", room_path(room) %>
  <h3>________________________________</h3>
<% end %>

<div>
  <%= link_to "Edit this hotel", edit_hotel_path(@hotel) %>--
  <%= link_to "Back to hotels", hotels_path %>--

  <%= button_to "Destroy this hotel", @hotel, method: :delete %>--
  <%= link_to "Add room For this Hotel", new_hotel_room_path(@hotel) %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotelpractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for [@hotel , @room], html: { class: 'form' } do |form| %>

  <div>
    <%= form.label :room_code%>
    <%= form.text_field :room_code%>
  </div>

  <div>
    <%= form.label :description%>
    <%= form.text_area :description%>
  </div>

  <div>
    <%= form.label :price_per_night%>
    <%= form.number_field :price_per_night%>
  </div>

  <div>
    <%= form.submit 'Save Room'%>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<h4>Room Code: <%= room.room_code %></h4>
<p>Description: <%= room.description %></p>
<p>Price per Night: <%= number_to_currency(room.price_per_night) %></p>

app/views/rooms/edit.html.erb
<h1>Edit Room For <%= @room.hotel.name %> Hotel</h1>

<%= render 'shared/errors', obj: @room %>
<%= render 'rooms/form' %>
<%= link_to 'Back to Hotel', :back %>

app/views/rooms/new.html.erb
<h1> Make room for this  <%= @hotel.name %> hotel</h1>

<%= render 'shared/errors', obj: @room %>
<%= render 'rooms/form' %>

app/views/rooms/show.html.erb
<%= render 'rooms/room', room: @room %>



<% @room.bookings.each do |booking| %>
  <h3>___________________________________</h3>
<%= render 'bookings/booking', booking: booking  %>

<% end %>

app/views/shared/_errors.html.erb
<% if obj && obj.errors.any? %>
<div>
    <h4><%= pluralize(obj.errors.count, 'error') %> prohibited this room from being saved:</h4>
    <ul>
        <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>